import { t } from "elysia";

export const GraphModel = {
  compileBody: t.Object({
    goalId: t.String(),
  }),
  runResponse: t.Object({ success: t.Boolean() }),
  policyTraceResponse: t.Object({
    decisions: t.Array(
      t.Object({
        id: t.String(),
        subjectType: t.String(),
        subjectId: t.String(),
        policySource: t.String(),
        decision: t.String(),
        reason: t.Optional(t.String()),
        rewrite: t.Optional(t.Record(t.String(), t.Unknown())),
        createdAt: t.String(),
      }),
    ),
    violations: t.Array(
      t.Object({
        id: t.String(),
        subjectType: t.String(),
        subjectId: t.String(),
        policySource: t.String(),
        reason: t.String(),
        metadata: t.Optional(t.Record(t.String(), t.Unknown())),
        createdAt: t.String(),
      }),
    ),
  }),
  traceEventResponse: t.Object({
    id: t.String(),
    nodeId: t.String(),
    attemptNumber: t.Number(),
    strategy: t.String(),
    status: t.String(),
    traceId: t.Optional(t.String()),
    inputSnapshotId: t.Optional(t.String()),
    outputSnapshotId: t.Optional(t.String()),
    latencyMs: t.Optional(t.Number()),
    tokenUsage: t.Optional(
      t.Object({
        input: t.Number(),
        output: t.Number(),
        total: t.Number(),
      }),
    ),
    costEstimateUsd: t.Optional(t.Number()),
    errorCode: t.Optional(t.String()),
    errorText: t.Optional(t.String()),
    startedAt: t.String(),
    finishedAt: t.Optional(t.String()),
  }),
  nodeResponse: t.Object({
    id: t.String(),
    graphId: t.String(),
    kind: t.String(),
    label: t.String(),
    status: t.String(),
    action: t.Optional(t.String()),
    assignedAgentName: t.Optional(t.String()),
    assignedRuntimeId: t.Optional(t.String()),
    input: t.Optional(t.Record(t.String(), t.Unknown())),
    output: t.Optional(t.Record(t.String(), t.Unknown())),
    policy: t.Optional(t.Record(t.String(), t.Unknown())),
    createdAt: t.String(),
    updatedAt: t.String(),
  }),
  edgeResponse: t.Object({
    id: t.String(),
    graphId: t.String(),
    fromNodeId: t.String(),
    toNodeId: t.String(),
    edgeType: t.String(),
    condition: t.Optional(t.Record(t.String(), t.Unknown())),
  }),
  graphResponse: t.Object({
    id: t.String(),
    goalId: t.String(),
    status: t.String(),
    version: t.String(),
    traceId: t.Optional(t.String()),
    contextSnapshotId: t.Optional(t.String()),
    createdAt: t.String(),
    updatedAt: t.String(),
    nodes: t.Array(
      t.Object({
        id: t.String(),
        graphId: t.String(),
        kind: t.String(),
        label: t.String(),
        status: t.String(),
        action: t.Optional(t.String()),
        assignedAgentName: t.Optional(t.String()),
        assignedRuntimeId: t.Optional(t.String()),
        input: t.Optional(t.Record(t.String(), t.Unknown())),
        output: t.Optional(t.Record(t.String(), t.Unknown())),
        policy: t.Optional(t.Record(t.String(), t.Unknown())),
        createdAt: t.String(),
        updatedAt: t.String(),
      }),
    ),
    edges: t.Array(
      t.Object({
        id: t.String(),
        graphId: t.String(),
        fromNodeId: t.String(),
        toNodeId: t.String(),
        edgeType: t.String(),
        condition: t.Optional(t.Record(t.String(), t.Unknown())),
      }),
    ),
  }),
  replayResponse: t.Object({
    graph: t.Any(),
    attempts: t.Array(t.Any()),
    context: t.Optional(t.Any()),
    reflections: t.Array(t.Any()),
    handoffs: t.Array(t.Any()),
    conflicts: t.Array(t.Any()),
  }),
  attemptDebugResponse: t.Object({
    attempt: t.Any(),
    inputSnapshot: t.Optional(t.Any()),
    outputSnapshot: t.Optional(t.Any()),
    reflection: t.Optional(t.Any()),
  }),
};
