import { t } from "elysia";

export const GraphModel = {
  compileBody: t.Object({
    goalId: t.String(),
  }),
  runResponse: t.Object({ success: t.Boolean() }),
  policyTraceResponse: t.Object({
    decisions: t.Array(
      t.Object({
        id: t.String(),
        subjectType: t.String(),
        subjectId: t.String(),
        policySource: t.String(),
        decision: t.String(),
        reason: t.Optional(t.String()),
        rewrite: t.Optional(t.Record(t.String(), t.Unknown())),
        createdAt: t.String(),
      }),
    ),
    violations: t.Array(
      t.Object({
        id: t.String(),
        subjectType: t.String(),
        subjectId: t.String(),
        policySource: t.String(),
        reason: t.String(),
        metadata: t.Optional(t.Record(t.String(), t.Unknown())),
        createdAt: t.String(),
      }),
    ),
  }),
  traceEventResponse: t.Object({
    id: t.String(),
    nodeId: t.String(),
    attemptNumber: t.Number(),
    strategy: t.String(),
    status: t.String(),
    errorCode: t.Optional(t.String()),
    errorText: t.Optional(t.String()),
    startedAt: t.String(),
    finishedAt: t.Optional(t.String()),
  }),
  nodeResponse: t.Object({
    id: t.String(),
    graphId: t.String(),
    kind: t.String(),
    label: t.String(),
    status: t.String(),
    action: t.Optional(t.String()),
    assignedAgentName: t.Optional(t.String()),
    assignedRuntimeId: t.Optional(t.String()),
    input: t.Optional(t.Record(t.String(), t.Unknown())),
    output: t.Optional(t.Record(t.String(), t.Unknown())),
    policy: t.Optional(t.Record(t.String(), t.Unknown())),
    createdAt: t.String(),
    updatedAt: t.String(),
  }),
  edgeResponse: t.Object({
    id: t.String(),
    graphId: t.String(),
    fromNodeId: t.String(),
    toNodeId: t.String(),
    edgeType: t.String(),
    condition: t.Optional(t.Record(t.String(), t.Unknown())),
  }),
  graphResponse: t.Object({
    id: t.String(),
    goalId: t.String(),
    status: t.String(),
    version: t.String(),
    createdAt: t.String(),
    updatedAt: t.String(),
    nodes: t.Array(
      t.Object({
        id: t.String(),
        graphId: t.String(),
        kind: t.String(),
        label: t.String(),
        status: t.String(),
        action: t.Optional(t.String()),
        assignedAgentName: t.Optional(t.String()),
        assignedRuntimeId: t.Optional(t.String()),
        input: t.Optional(t.Record(t.String(), t.Unknown())),
        output: t.Optional(t.Record(t.String(), t.Unknown())),
        policy: t.Optional(t.Record(t.String(), t.Unknown())),
        createdAt: t.String(),
        updatedAt: t.String(),
      }),
    ),
    edges: t.Array(
      t.Object({
        id: t.String(),
        graphId: t.String(),
        fromNodeId: t.String(),
        toNodeId: t.String(),
        edgeType: t.String(),
        condition: t.Optional(t.Record(t.String(), t.Unknown())),
      }),
    ),
  }),
};
